version: '3'
services:
  app:
    build: .
    container_name: zeycake-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=Clesecretezeycake
      - DATABASE_URL=file:./database.sqlite
