name: ci-backend

on:
  push:
    branches: [ new-branch ]
  pull_request:
    branches: [ new-branch ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      JWT_SECRET: superSecret
      JWT_EXPIRES_IN: 7d
      MONGO_URI: mongodb://localhost:27017/zeycake-test  # utilisé par ton code si tu le lis

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Installer les dépendances du backend
        run: npm ci
        working-directory: backend

      - name: Lancer les tests avec couverture
        run: npm run test:ci
        working-directory: backend

      - name: Upload couverture
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: couverture-backend
          path: backend/coverage
